### PR TITLE
Feature/270 exercise improvement

### PR DESCRIPTION
**Pull request by celopacob**
https://github.com/cybsafe/phishtray/issues/270

### CODE REVIEW

**Comment by fericsepi** [comment]
Looks good, 2 remarks:
- [ ]  Admins that should not be able to save public exercise that don't belong to their organisation
- [ ]  Admins should be able to edit the exercise that they just copied from a public exercise

**Comment by fericsepi** [comment]
Found one more item:
- [ ] When clicking the `Delete` button in Edit exercise view it doesn't delete the Exercise, only scrolls to the top of the page

**Comment by celopacob** [comment]
Also Excluding soft deleted items from the queryset

**Comment by fericsepi** [comment]
Looks good!

**Pull request merged**
